name: Feature Request
description: Propose a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature description
  - type: textarea
    attributes:
      label: Why is it useful?
  - type: textarea
    attributes:
      label: Alternative solutions
  - type: textarea
    attributes:
      label: Additional information
