apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qoptisolve-ingress
spec:
  rules:
    - host: api.qoptisolve.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qoptisolve-service
                port:
                  number: 80
